name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: nr1
        run: |
          npm i -g nr1
          nr1 nerdpack:info
          echo $?

      - name: check
        run: |

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 2

      - name: Run a multi-line script
        if: success()
        run: |
          echo 3

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 4
