name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: exit 1

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 1

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 2

      - name: Run a multi-line script
        if: success()
        run: |
          echo 3

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 4
