name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: nr1
        continue-on-error: true
        env:
          NR_USER_KEY: ${{ secrets.NR_USER_KEY }}
        id: nr1
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash
          nr1 profiles:add --name tmp --api-key $NR_USER_KEY --region us
          nr1 nerdpack:info
          echo '::set-output name=NOT_REGS::'$?

      - name: check
        run: |
          echo "hoge"${{ steps.nr1.output.NOT_REGS }}
          nr1 nerdpack:info

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 2

      - name: Run a multi-line script
        if: success()
        run: |
          echo 3

      - name: Run a multi-line script
        if: failure()
        run: |
          echo 4
